Feature/conf add inf
devops2024-group-e/itu-minitwit pull request #186
Opened 2024-03-20 12:52 UTC by Pinkvinus

# What
We wanted to set up SSH s.t. the conf server can ssh into production servers and manage them

# How
We added support for creation of ssh keys and giving the public key to DO. Furthermore, a `Conf-management` token has been made on DO which allows the server to do send it's ssh key to DO.
![image](https://github.com/devops2024-group-e/itu-minitwit/assets/74830754/255c6053-6bac-4da9-93b5-0a1adbe33474)

> [!NOTE]
> You need to have added the `CONF_DO_TOKEN` to your `.bashrc`

This PR closes #181

2024-03-20 14:16 UTC, arnenator requested changes
I like that you create a new ssh key in the provisioning script. I think that is very nice! However, I still think that there are some loose ends

2024-03-20 14:16 UTC, arnenator commented on Vagrantfile
> +    mkdir ~/.config
What do we use this directory for? It does not seem to be referenced either in the provisioning script? Do we use it?

2024-03-20 14:16 UTC, arnenator commented on Vagrantfile
> +    sudo snap install doctl
Isn't it possible to install doctl via apt-get? Why do we need another package management tool?

2024-03-20 14:16 UTC, arnenator commented on Vagrantfile
> +    server.vm.provision "shell", inline: 'echo "export CONF_DO_TOKEN=' + "'" + ENV["CONF_DO_TOKEN"] + "'" + '" >> ~/.bash_profile'
I guess this contains the token that you use to login to digital ocean?

2024-03-20 14:16 UTC, arnenator commented on Vagrantfile
> +    doctl compute ssh-key create ConfigManagement --public-key "$(cat ~/.ssh/do_ssh_key.pub)"
So you create a new SSH key... very nice! However, I have one question! Do you remember to set the environment variable `DIGITAL_OCEAN_SSH_KEY_NAME` on the server as well? We need that in order to create and provision the other servers that the ansible server is going to use.

2024-03-20 14:55 UTC, Pinkvinus commented on Vagrantfile
> +    mkdir ~/.config
It is because the doctl references it, and because its installed using snap it cant initialise this directory itself. Therefore, in order for doctl to work, this directory needs to exist

2024-03-20 14:56 UTC, Pinkvinus commented on Vagrantfile
> +    sudo snap install doctl
You can't get it using sudo apt get to my knowledge. i did try. The alternative would be to do a manual install

2024-03-20 14:56 UTC, Pinkvinus commented on Vagrantfile
> +    server.vm.provision "shell", inline: 'echo "export CONF_DO_TOKEN=' + "'" + ENV["CONF_DO_TOKEN"] + "'" + '" >> ~/.bash_profile'
Yes. The token itself is in notion

2024-03-20 14:57 UTC, Pinkvinus commented on Vagrantfile
> +    doctl compute ssh-key create ConfigManagement --public-key "$(cat ~/.ssh/do_ssh_key.pub)"
Not currently, but we can simply just add that, as the ssh keyname will always be the same

2024-03-20 15:03 UTC, arnenator commented on Vagrantfile
> +    sudo snap install doctl
Okay 😄

2024-03-20 15:04 UTC, arnenator commented on Vagrantfile
> +    server.vm.provision "shell", inline: 'echo "export CONF_DO_TOKEN=' + "'" + ENV["CONF_DO_TOKEN"] + "'" + '" >> ~/.bash_profile'
Cool

2024-03-20 15:04 UTC, arnenator commented on Vagrantfile
> +    doctl compute ssh-key create ConfigManagement --public-key "$(cat ~/.ssh/do_ssh_key.pub)"
Okay... so we need to do that in the provisioning script you have created in the vagrantfile

2024-03-21 15:33 UTC, arnenator approved these changes

2024-03-21 15:33 UTC, merged