Add github tool description
devops2024-group-e/itu-minitwit pull request #332
Opened 2024-05-16 14:08 UTC by arnenator

2024-05-16 19:11 UTC, Pinkvinus requested changes

2024-05-16 19:11 UTC, Pinkvinus commented on report/sections/system-perspective/Dependencies-technologies-tools.tex
> +    Remote Repository and work tracking and coordination & \href{https://github.com/features}{GitHub} & GitHub serves as remote Git repoistory. It comes with collaborative features such as, having wo
This title needs a comma somewhere depending on what you mean.

2024-05-16 19:11 UTC, Pinkvinus commented on report/sections/system-perspective/Dependencies-technologies-tools.tex
> +    Remote Repository and work tracking and coordination & \href{https://github.com/features}{GitHub} & GitHub serves as remote Git repoistory. It comes with collaborative features such as, having wo
, ~~and~~ etc.

2024-05-16 19:11 UTC, Pinkvinus commented on report/sections/system-perspective/Dependencies-technologies-tools.tex
> +    Remote Repository and work tracking and coordination & \href{https://github.com/features}{GitHub} & GitHub serves as remote Git repoistory. It comes with collaborative features such as, having wo
~~GitHub is the tool we use, because it provides the collaborative features that we need and have experience with it\\~~
-> We use GitHub, as it provides collaborative [...] .\\

2024-05-16 20:25 UTC, Myssenberg requested changes

2024-05-16 20:25 UTC, Myssenberg commented on report/sections/system-perspective/Dependencies-technologies-tools.tex
Take this:

GitHub serves as a remote Git repository. It comes with collaborative features, such as having work items (known as issues), project coordination boards, CI/CD workflows, etc. We use GitHub, as the group has experience with the tool and it provides the collaborative features we need.

2024-05-16 20:26 UTC, arnenator commented on report/sections/system-perspective/Dependencies-technologies-tools.tex
Already done

2024-05-16 20:28 UTC, Myssenberg commented on report/sections/system-perspective/Dependencies-technologies-tools.tex
I don't see the changes in the files though. Do you mean that you already did the section or you pasted the thing I edited in?

2024-05-16 20:39 UTC, arnenator commented on report/sections/system-perspective/Dependencies-technologies-tools.tex
Look again

2024-05-16 20:44 UTC, Myssenberg approved these changes
Nice work!!

2024-05-17 11:36 UTC, Pinkvinus approved these changes

2024-05-17 11:36 UTC, merged