MessageRepository and UserRepository
devops2024-group-e/itu-minitwit pull request #92
Opened 2024-03-01 15:07 UTC by amalieboegild

Repository has been added for User and Message. Also, i've made two projects: one for repositories (Infrastructure) and one for tests of the infrastructure. I will fill in tests for the two repositories next week.

2024-03-01 17:08 UTC, Arneproductions requested changes
Very nice so far! You need to create interfaces for the repositories that the rest of the code should depend upon. Also we need to register these dependencies in the `Program.cs` with `services.AddScoped()` such that the Dependency Injection system knows which class to create when it initializes an instance of a controller.

Nice work! 🔥 🔥 🔥

2024-03-01 17:08 UTC, Arneproductions commented on Minitwit/Controllers/RegisterController.cs
> +    public RegisterController(ILogger<RegisterController> logger, UserRepository userRepository)
Very nice that you add it to the constructor. But we have to abstract the details a bit further. You need to create an interface to the `UserRepository` called `IUserRepository`. This is so that when we want to change databases or framework we can do that easily and still adhere to the interface that the rest of the code is depending on

2024-03-01 17:08 UTC, Arneproductions commented on Minitwit/Controllers/TimelineController.cs
> +    public TimelineController(ILogger<TimelineController> logger, MinitwitContext context, MessageRepository messageRepository, UserRepository userRepository)
Same thing here as the last comment we need to change this to be depending on interfaces

2024-03-07 19:48 UTC, Arneproductions commented
I can see that you have some issues passing the checks. To be more specific, we now know that the integration tests works. The reason why the integration tests fails is because you use some aggregation methods that `pgsql`i.e. the postgres linq provider does not support. 

Let us take a look at it tomorrow and fix it together

2024-03-11 09:54 UTC, Myssenberg commented
All repositories + tests should be added and be working with the integrations tests now. We just have to fix the merge conflicts with main.

2024-03-11 11:05 UTC, Pinkvinus requested changes
All workflows that handle changes in the projects need to be updated with the new path as well

2024-03-11 16:12 UTC, Arneproductions approved these changes
I essentially have some suggestions that could be changed. However, it is cosmetics. So if you do not want to change them then please create an issue on the board and then we will prioritize it.

Nice work from both of you ✨

2024-03-11 16:12 UTC, Arneproductions commented on MinitwitSimulatorAPI/Program.cs
>  builder.Services.AddControllers();
Can you move these such that it is together with the other Dependency Injected Repository classes at line 39 and 40?

2024-03-11 16:12 UTC, Arneproductions commented on Minitwit/Program.cs
> +builder.Services.AddScoped<IUserRepository, UserRepository>();
Can you move these lines closer to be underneath line 20?

2024-03-11 16:14 UTC, Arneproductions commented on .github/workflows/Testing.yaml
> +      - 'Minitwit.Infrastructure/**'
I agree

2024-03-12 16:52 UTC, Pinkvinus commented on Minitwit/ViewModels/PublicTimelineViewModel.cs
> +using Minitwit.Infrastructure.Models;
What exactly is the point of saying this uses the new abstraction layer if it is never used in the code?

2024-03-12 16:52 UTC, Pinkvinus commented on Minitwit/ViewModels/TimelineViewModel.cs
> +using Minitwit.Infrastructure.Models;
Same as before

2024-03-12 16:55 UTC, Pinkvinus approved these changes
Only have one minor comment. Nothing big tho

2024-03-12 17:19 UTC, merged